# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GITHUB_VERSION: 0.0.0
  LOGSTASH_VERSION: 7.6.2
  OPENJDK_AWS_VERSION: latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: 폴더 생성
      run: |
        mkdir temp
        mkdir logstash
        mkdir openjdk
    - name: pandoc 설치
      run: |
        choco install -g -y -f pandoc        
    - name: pandoc 생성
      run: |
        pandoc -s bluecats/manual/readme.md -o bluecats/manual/readme.html
    - name: logstash-oss 다운로드
      run: |
        Invoke-WebRequest https://artifacts.elastic.co/downloads/logstash/logstash-oss-$env:LOGSTASH_VERSION.zip -OutFile temp/logstash-oss.zip
    - name: logstash-oss 압축 해제
      run: |
        Expand-Archive -Path temp/logstash-oss.zip -DestinationPath logstash
    - name: Amazon Corretto 다운로드
      run: |
        Invoke-WebRequest https://corretto.aws/downloads/$env:OPENJDK_AWS_VERSION/amazon-corretto-11-x64-windows-jdk.zip -OutFile temp/java.zip
    - name: Amazon Corretto 압축 해제
      run: |
        Expand-Archive -Path temp/java.zip -DestinationPath openjdk
    - name: bluecats 설정 overwrite 파일 복사
      run: |
        Move-Item -Path logstash/logstash-$env:LOGSTASH_VERSION release
        Move-Item -Path openjdk/jdk11.0.7_10 release/java
        Copy bluecats\* release -Recurse -Force
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: bluecats-hub
        # Directory containing files to upload
        path: ./release