name: Release

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_VERSION: 0.0.0
  LOGSTASH_VERSION: 7.6.2
  OPENJDK_AWS_VERSION: latest

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: seungyongshim/get-version-action@v1.3
    - id: get_release
      uses: bruceadams/get-release@v1.2.0        
    - name: 폴더 생성
      run: |
        mkdir temp
        mkdir logstash
        mkdir openjdk
    - name: logstash-oss 다운로드
      run: |
        Invoke-WebRequest https://artifacts.elastic.co/downloads/logstash/logstash-oss-$env:LOGSTASH_VERSION.zip -OutFile temp/logstash-oss.zip
    - name: logstash-oss 압축 해제
      run: |
        Expand-Archive -Path temp/logstash-oss.zip -DestinationPath logstash
    - name: Amazon Corretto 다운로드
      run: |
        Invoke-WebRequest https://corretto.aws/downloads/$env:OPENJDK_AWS_VERSION/amazon-corretto-11-x64-windows-jdk.zip -OutFile temp/java.zip
    - name: Amazon Corretto 압축 해제
      run: |
        Expand-Archive -Path temp/java.zip -DestinationPath openjdk
    - name: bluecats 설정 overwrite 파일 복사
      run: |
        Move-Item -Path logstash/logstash-$env:LOGSTASH_VERSION release
        Move-Item -Path openjdk/jdk11.0.7_10 release/java
        Copy bluecats\* release -Recurse -Force
        Remove-Item release\config\* -Recurse -Force
        Remove-Item release\config
    - name: Compress Release
      run: Get-ChildItem release | Compress-Archive -DestinationPath "bluecats_hub.zip"
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: bluecats_hub.zip
        asset_name: bluecats_hub.zip
        asset_content_type: application/zip
 